### ISSUE TITLE
Adding methods related to user and visitor identification

### ISSUE THREAD

**Issue by matthias-prevost** [at-internet/piano-analytics-flutter#1]
Hi,

Following the piano.io developers documentation, there are methods that enable setting user/visitor related properties : 

- [visitor identification](https://developers.atinternet-solutions.com/piano-analytics/data-collection/how-to-send-events/visitor-identification)
- [user properties](https://developers.atinternet-solutions.com/piano-analytics/data-collection/how-to-send-events/users)

These are only available in Javascript and native SDKs, is there any chance that you will bridge them in the Flutter SDK ? 
If so, when do you plan it to be released ?

Thanks !

**Comment by BenDz** [comment]
Hi @matthias-prevost 
v1.0.1 has been released, with these new features.
